[project]
channels = ["conda-forge"]
name = "internship_2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
absl-py = ">=2.3.0,<3"
anyio = ">=4.9.0,<5"
argon2-cffi = ">=25.1.0,<26"
argon2-cffi-bindings = ">=21.2.0,<22"
astunparse = ">=1.6.3,<2"
attrs = ">=25.3.0,<26"
babel = ">=2.17.0,<3"
backcall = ">=0.2.0,<0.3"
bleach = ">=6.2.0,<7"
cached-property = ">=1.5.2,<2"
cachetools = ">=5.5.2,<6"
certifi = ">=2025.6.15,<2026"
cffi = ">=1.17.1,<2"
cftime = ">=1.6.4,<2"
charset-normalizer = ">=3.4.2,<4"
clang = ">=20.1.7,<21"
comm = ">=0.2.2,<0.3"
contextvars = ">=2.4,<3"
cycler = ">=0.12.1,<0.13"
dataclasses = ">=0.8,<0.9"
decorator = ">=5.2.1,<6"
defusedxml = ">=0.7.1,<0.8"
entrypoints = ">=0.4,<0.5"
flatbuffers = ">=24.12.23,<25"
gast = ">=0.6.0,<0.7"
google-auth = ">=2.40.3,<3"
google-auth-oauthlib = ">=1.2.2,<2"
google-pasta = ">=0.2.0,<0.3"
grpcio = ">=1.67.1,<2"
h5py = ">=3.14.0,<4"
idna = ">=3.10,<4"
immutables = ">=0.21,<0.22"
importlib-metadata = ">=8.7.0,<9"
jedi = ">=0.19.2,<0.20"
jinja2 = ">=3.1.6,<4"
joblib = ">=1.5.1,<2"
json5 = ">=0.12.0,<0.13"
jsonschema = ">=4.24.0,<5"
keras = ">=3.10.0,<4"
keras-preprocessing = ">=1.1.2,<2"
kiwisolver = ">=1.4.8,<2"
markdown = ">=3.8.2,<4"
markupsafe = ">=3.0.2,<4"
matplotlib = ">=3.10.3,<4"
mistune = ">=3.1.3,<4"
nbclassic = ">=1.3.1,<2"
nbclient = ">=0.10.2,<0.11"
nbconvert = ">=7.16.6,<8"
nbformat = ">=5.10.4,<6"
nest-asyncio = ">=1.6.0,<2"
netcdf4 = ">=1.7.2,<2"
notebook = ">=7.4.4,<8"
numpy = ">=2.3.1,<3"
oauthlib = ">=3.3.1,<4"
opt-einsum = ">=3.4.0,<4"
packaging = ">=25.0,<26"
pandas = ">=2.3.0,<3"
pandocfilters = ">=1.5.0,<2"
parso = ">=0.8.4,<0.9"
pexpect = ">=4.9.0,<5"
pickleshare = ">=0.7.5,<0.8"
pillow = ">=11.2.1,<12"
prompt-toolkit = ">=3.0.51,<4"
protobuf = ">=5.28.3,<6"
ptyprocess = ">=0.7.0,<0.8"
pyasn1 = ">=0.6.1,<0.7"
pyasn1-modules = ">=0.4.2,<0.5"
pycparser = ">=2.22,<3"
pygments = ">=2.19.2,<3"
pyparsing = ">=3.2.3,<4"
pyrsistent = ">=0.20.0,<0.21"
python-dateutil = ">=2.9.0.post0,<3"
pytz = ">=2025.2,<2026"
pyzmq = ">=27.0.0,<28"
requests = ">=2.32.4,<3"
requests-oauthlib = ">=2.0.0,<3"
rsa = ">=4.9.1,<5"
scikit-learn = ">=1.7.0,<2"
scipy = ">=1.16.0,<2"
send2trash = ">=1.8.3,<2"
six = ">=1.17.0,<2"
sniffio = ">=1.3.1,<2"
tensorboard = ">=2.18.0,<3"
tensorboard-data-server = ">=0.7.0,<0.8"
tensorboard-plugin-wit = ">=1.8.1,<2"
tensorflow = ">=2.18.0,<3"
tensorflow-estimator = ">=2.18.0,<3"
termcolor = ">=3.1.0,<4"
terminado = ">=0.18.1,<0.19"
testpath = ">=0.6.0,<0.7"
threadpoolctl = ">=3.6.0,<4"
tornado = ">=6.5.1,<7"
traitlets = ">=5.14.3,<6"
typing-extensions = ">=4.14.0,<5"
urllib3 = ">=2.5.0,<3"
wcwidth = ">=0.2.13,<0.3"
webencodings = ">=0.5.1,<0.6"
websocket-client = ">=1.8.0,<2"
werkzeug = ">=3.1.3,<4"
wfdb = ">=4.3.0,<5"
widgetsnbextension = ">=4.0.14,<5"
wrapt = ">=1.17.2,<2"
xarray = ">=2025.6.1,<2026"
zipp = ">=3.23.0,<4"
pyyaml = "6.0.1.*"
nbstripout = "0.6.2.*"
