[workspace]
authors = ["Sonia Hasko <sh2968@princeton.edu>"]
channels = ["conda-forge"]
name = "internship_2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
tensorflow = ">=2.18.0,<3"
numpy = ">=2.3.1,<3"
xarray = ">=2025.7.1,<2026"
netcdf4 = ">=1.7.2,<2"
scikit-learn = ">=1.7.1,<2"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.3.1,<3"
